name: .NET Core

on: [push]

jobs:
  build:
    name: Test on dotnet ${{ matrix.dotnet_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet_version: ['2.2.108']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core ${{ matrix.dotnet_version}}
      uses: actions/setup-dotnet@v1
      with:
        node-version: ${{ matrix.dotnet_version}}
    - name: Build with dotnet
      run: dotnet build --configuration Release
