---
name: release linux

on: [push]

jobs:
  build-artifact:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet_version: ['6.0.x']
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v1
        with:
          nim-version: ${{ matrix.dotnet_version}}
      - run: cd src && dotnet build --configuration Release
      - name: Create artifact linux
        run: |
          echo "restoring packeges"
          dotnet restore src/LacmusApp.sln
          echo -n "building for linux"
          dotnet publish --framework net6.0 --runtime="linux-x64" -c Release -o bin src/LacmusApp.sln
          mv bin/LacmusApp.Avalonia bin/LacmusApp
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-linux
          path: |
            bin/
  